### ISSUE TITLE
Is this extension ready for MW / WB 1.36?

### ISSUE THREAD

**Issue by addshore** [ProfessionalWiki/WikibaseLocalMedia#10]
Reading the readme currently 1.34/1.35 are specifically mentioned.
Should this also work with 1.36?
Do we just need to fix the docs or also do some additional testing etc first?

**Comment by JeroenDeDauw** [comment]
Seems like it does not work with master since 4 months ago: https://github.com/ProfessionalWiki/WikibaseLocalMedia/actions

Not tested anywhere with WB 36, probably does not work without some fixing.
