### ISSUE TITLE
Is there a plan to enable wiki/Special:Licenses support in Wikibase to compliment this extension?

### ISSUE THREAD

**Issue by ross-spencer** [ProfessionalWiki/WikibaseLocalMedia#11]
From what I can tell, Wikibase doesn't support the Special:License page. Because of this, files can be uploaded but a license cannot be assigned to them. Is that a correct reading, and is it likely the feature can be enabled in someway via this initiative?

**Comment by JeroenDeDauw** [comment]
While I am not familiar with Special:Licenses, the answer to your question is very likely "no". This extension does not deal with file upload. It just allows using files that where already uploaded to your wiki.

Perhaps there is room for better file upload integration in Wikibase, and perhaps this extension is a sensible place for that. This is however not a small task.

**Comment by ross-spencer** [comment]
Thanks @JeroenDeDauw, and I appreciate the clarification around workflow here. That makes a lot of sense. I'll probe a little more around the Wikibase use-case/decisions around this. Thanks again for the feedback.

**Comment by ross-spencer** [comment]
Okay, I understand now, this is the documentation: https://www.mediawiki.org/wiki/Manual:Image_administration#Licensing 

So if my wiki is `http://example.com/wiki` - I can edit `http://example.com/wiki:MediaWiki:Licenses` I can then do something like add the source for: https://commons.wikimedia.org/w/index.php?title=MediaWiki:Licenses&action=edit

And I can see the result in the Upload page. E.g. 

![image](https://user-images.githubusercontent.com/1880412/133439862-350f2586-d7e6-41c1-aaac-6f33f6ef1e7b.png)

This will work.
