### ISSUE TITLE
Compatibility with federated properties in 1.35?

### ISSUE THREAD

**Issue by ross-spencer** [ProfessionalWiki/WikibaseLocalMedia#12]
It seems with the new setting in 1.35: `$wgWBRepoSettings['federatedPropertiesEnabled'] = true;` that creating a wiki with this enabled will mean that a property for local media cannot be created. Is that correct? Does it mean that this feature/extension cannot be used with federated properties at all? Is there a way the extension can be developed to work alongside federated properties?

**Comment by JeroenDeDauw** [comment]
Last time I looked at federated properties, it was a switch being supporting only remote or only local properties. Perhaps that is no longer the case with latest Wikibase, but I'd be surprised if it was different with 1.35. In which case support in this extension is moot, combining local and remote won't work either way.
