### ISSUE TITLE
Manual installation => Fatal error occurs

### ISSUE THREAD

**Issue by shigapov** [ProfessionalWiki/WikibaseLocalMedia#7]
### Setup

- Wikibase Local Media version: the latest from GitHub, 1.0.1?
- Wikibase version: 1.35
- MediaWiki version: 1.35.1
- PHP version: 7.3.26

### Issue

Tried to install WikibaseLocalMedia manually. Added `wfLoadExtension( 'WikibaseLocalMedia' );` to `LocalSettings.php.template` at [RaiseWikibase](https://github.com/UB-Mannheim/RaiseWikibase) and mounted folder `WikibaseLocalMedia` to `/var/www/html/extensions/WikibaseLocalMedia`.

I cannot open localhost:8181, the error occurs:

`Fatal error: Uncaught UnexpectedValueException: callback 'Wikibase\LocalMedia\HookHandlers::onExtensionRegistration' is not callable in /var/www/html/includes/registration/ExtensionRegistry.php:539 Stack trace: #0 /var/www/html/includes/registration/ExtensionRegistry.php(232): ExtensionRegistry->exportExtractedData(Array) #1 /var/www/html/includes/Setup.php(161): ExtensionRegistry->loadFromQueue() #2 /var/www/html/includes/WebStart.php(89): require_once('/var/www/html/i...') #3 /var/www/html/index.php(44): require('/var/www/html/i...') #4 {main} thrown in /var/www/html/includes/registration/ExtensionRegistry.php on line 539`

**Comment by JeroenDeDauw** [comment]
Not sure why that happened. Basically a MediaWiki question and not specific to this extension.

I've removed the bit that was breaking since it was not used anyway. Perhaps the extension loading works now, or perhaps another bit will error out.

**Comment by shigapov** [comment]
Okay, it seems the problem was in permissions. Normally, when I download an extension folder at [Mediawiki](https://www.mediawiki.org/wiki/Manual:Extensions), there are access permissions for groups and others. I downloaded WikibaseLocalMedia from GitHub and I needed to set the permissions. That's it, now it works. Thank you for the extension!

I have not tested your recent changes.
